version: "3.4"

services: 
  app:
    build: .
    restart: always
    volumes: 
      - ./:/app
    ports: 
      - 7777:7777

  database:
    container_name: "postgres-database"
    image: "postgres:13.1"
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432